### ISSUE TITLE
Edits not being saved?

### ISSUE THREAD

**Issue by NECKRHINOS** [ezraverheijen/kirby-robots.txt#2]
Hi @ezraverheijen , first of all: Thanks for the plugin. However I have trouble getting it to work the way I think it's supposed to be? When I edit the content of the file in the panel, that doesn't seem to get saved. By going to my-url.com/robots.txt I only get to download a txt file with no content being changed via panel.

```
Toolkit Version: 2.5.4
Kirby Version: 2.5.4
Panel Version: 2.5.4
```
```
c::set('cache.ignore', array('robotstxt'));
c::set('sitemap.exclude', array('error', 'robotstxt'));
```

What does the 'virtual' part mean exactly? Is it indexed by search engines as normal? How can I look up and check the txt file created via panel?

**Comment by ezraverheijen** [comment]
Hi @NECKRHINOS,
The robots.txt file produced by the plugin is not a real text file, but a virtual one. The URL "/robots.txt" routes to some functionality that grabs the text from the panel (rules for the crawlers) and spits it out along with a 'text/plain' HTTP header. My plugin just mimics an actual text file.
